---
name: Deploy

on:
  workflow_call:
    inputs:
      subscriptionId:
        required: true
        type: string
      environmentIdentifier:
        required: true
        type: string
      location:
        required: true
        type: string
      applicationRegistration:
        required: true
        type: string
      gitHubRepoName:
        required: true
        type: string
      gitHubOrganisation:
        required: true
        type: string

    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true

permissions:
  contents: read # Required to read the repository's contents
  id-token: write # This is required for azure/login

env:
  deploymentJobId: "deploy-rg-${{ github.run_id }}"

jobs:
  deploy:
    name: deploy
    environment: ${{ inputs.environmentIdentifier }}
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Az Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true

      - name: Create Application Registration and Federated Identity - ${{ inputs.environmentIdentifier }}
        uses: azure/powershell@v2
        with:
          inlineScript: |
            # Install-Module Microsoft.Graph -Force -verbose
            # Get-Module Microsoft.Graph
            # Import-Module Microsoft.Graph -Force
            $AccessToken = (Get-AzAccessToken -ResourceUrl "https://graph.microsoft.com").Token
            (Get-AzAccessToken -ResourceUrl "https://graph.microsoft.com").Token
            $sec = ConvertTo-SecureString $AccessToken -AsPlainText -Force
            Connect-MgGraph -AccessToken $sec -NoWelcome
            Import-Module Microsoft.Graph.Applications
            $appName = "${{ inputs.applicationRegistration }}"
            $myApp = Get-MgApplication -Filter "DisplayName eq '$appName'" -ErrorAction SilentlyContinue        
            if ($myApp) {
                Write-Host "Application Registration $appName already exists. Skipping creation..."
            } else {
                $myApp = New-MgApplication -DisplayName "$appName"
                Write-Host "Application Registration $appName created successfully."
            }
            $myApp 
            start-sleep -Seconds 300
            $subscriptionId = (Get-AzContext).Subscription.Id
            $tenantId = (Get-AzContext).Subscription.TenantId
            $githubOrganisation = "${{ env.gitHubOrganisation}}"
            $githubRepo = "${{ inputs.gitHubRepoName}}"
            $gitBranch = "main"
            $gitFederationName = "federated-credentials-${{ inputs.workloadShortName }}"
            $clientId = $myApp.id
            $policy = "repo:$githubOrganisation/$($githubRepo):ref:refs/heads/$gitBranch"
            $creds = get-MgApplicationFederatedIdentityCredential -ApplicationId $myApp.id | where-object {$_.Subject -eq $policy}
            if($creds){
              Write-Host "Workload identity federation $policy already exists. Skipping creation..."
            } else {
              $federatedApp = New-MgApplicationFederatedIdentityCredential -ApplicationId $clientId `
              -Audiences api://AzureADTokenExchange -Issuer "https://token.actions.githubusercontent.com" -Name $gitFederationName -Subject $policy
            }
            echo "devObjectId=$myApp.ObjectId" >> $env:GITHUB_ENV

          azPSVersion: latest

      - name: whatIf
        uses: azure/bicep-deploy@v2
        with:
          operation: whatIf
          type: deployment
          name: main-${{env.deploymentJobId}}
          location: ${{inputs.location}}
          scope: subscription
          subscription-id: ${{ inputs.subscriptionId }}
          parameters-file: ./deployment/parameters.bicepparam

      - name: Deploy
        uses: azure/bicep-deploy@v2
        with:
          operation: create
          type: deployment
          name: main-${{env.deploymentJobId}}
          location: ${{inputs.location}}
          scope: subscription
          subscription-id: ${{ inputs.subscriptionId }}
          parameters-file: ./deployment/parameters.bicepparam

      # Log out of Azure
      - name: Az Logout
        run: az logout
