name: Resource Group Deployment Onboarding

on:
  workflow_dispatch:
    inputs:
      environmentIdentifier:
        description: "Please select the environment identifier"
        type: choice
        required: True
        options:
          - "sbx"
          - "dev"
          - "tst"
          - "prd"

      location:
        description: "Please select the Azure region."
        type: choice
        required: True
        options:
          - australiaeast
          - australiasoutheast

      workloadShortName:
        description: "Workload Short Name"
        type: string
        required: True
        default: ""

      gitHubRepoName:
        description: "GitHub Repository Name"
        type: string
        required: True
        default: ""

env:
  deploymentJobId: "deploy-rg-${{ github.run_id }}"
  gitHubOrganisation: "tulpy"
  oidcAppRegClientId: "a7164fc2-e53c-48a0-8ef8-13c558a9ea95"
  tenantId: "a2ebc691-c318-4ec2-998a-a87c528378e0"
  sbxSubscriptionId: "0b5d0018-2879-4810-b8d7-4f8dda5ce0b9"
  devSubscriptionId: "0b5d0018-2879-4810-b8d7-4f8dda5ce0b9"
  tstSubscriptionId: "0b5d0018-2879-4810-b8d7-4f8dda5ce0b9"
  prdSubscriptionId: "0b5d0018-2879-4810-b8d7-4f8dda5ce0b9"
  spnSbxName: "app-reg-github-${{ inputs.workloadShortName }}-sbx"
  spnDevName: "app-reg-github-${{ inputs.workloadShortName }}-dev"
  spnTstName: "app-reg-github-${{ inputs.workloadShortName }}-tst"
  spnPrdName: "app-reg-github-${{ inputs.workloadShortName }}-prd"

jobs:
  deploy:
    name: Deploy
    runs-on: windows-latest
    environment: '${{ inputs.environmentIdentifier }}'
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2.2.0
        with:
          client-id: ${{ env.oidcAppRegClientId }}
          tenant-id: ${{ env.tenantId }}
          allow-no-subscriptions: true
          enable-AzPSSession: true

      - name: Create Application Registration and Federated Identity - DEV
        if: inputs.environmentIdentifier == 'tst'
        uses: azure/powershell@v2
        with:
          inlineScript: |
            # Install-Module Microsoft.Graph -Force -verbose
            # Get-Module Microsoft.Graph
            # Import-Module Microsoft.Graph -Force
            $AccessToken = (Get-AzAccessToken -ResourceUrl "https://graph.microsoft.com" -AsSecureString).Token
            (Get-AzAccessToken -ResourceUrl "https://graph.microsoft.com" -AsSecureString).Token
            $sec = ConvertTo-SecureString $AccessToken -AsPlainText -Force
            Connect-MgGraph -AccessToken $sec -NoWelcome
            Import-Module Microsoft.Graph.Applications
            $appName = "${{ env.spnDevName }}"
            $myApp = Get-MgApplication -Filter "DisplayName eq '$appName'" -ErrorAction SilentlyContinue        
            if ($myApp) {
                Write-Host "Application Registration $appName already exists. Skipping creation..."
            } else {
                $myApp = New-MgApplication -DisplayName "$appName"
                Write-Host "Application Registration $appName created successfully."
            }
            $myApp 
            start-sleep -Seconds 300
            $subscriptionId = (Get-AzContext).Subscription.Id
            $tenantId = (Get-AzContext).Subscription.TenantId
            $githubOrganisation = "tulpy"
            $githubRepo = "${{ inputs.gitHubRepoName}}"
            $gitBranch = "main"
            $gitFederationName = "federated-credentials-${{ inputs.workloadShortName }}"
            $clientId = $myApp.id
            $policy = "repo:$githubOrganisation/$($githubRepo):ref:refs/heads/$gitBranch"
            $creds = get-MgApplicationFederatedIdentityCredential -ApplicationId $myApp.id | where-object {$_.Subject -eq $policy}
            if($creds){
              Write-Host "Workload identity federation $policy already exists. Skipping creation..."
            } else {
              $federatedApp = New-MgApplicationFederatedIdentityCredential -ApplicationId $clientId `
              -Audiences api://AzureADTokenExchange -Issuer "https://token.actions.githubusercontent.com" -Name $gitFederationName -Subject $policy
            }
            echo "devObjectId=$myApp.ObjectId" >> $env:GITHUB_ENV

          azPSVersion: latest

      - name: Create the Resource Group - DEV
        if: inputs.environmentIdentifier == 'tst'
        run: |
          az account set --subscription  ${{ env.devSubscriptionId }}
          az deployment sub create `
          --name ${{ env.deploymentJobId }} `
          --location ${{ inputs.location }} `
          --subscription ${{ env.devSubscriptionId }} `
          --parameters ./deployment/parameters.bicepparam
        shell: pwsh