name: Resource Group Deployment Onboarding

on:
  workflow_dispatch:
    inputs:
      environmentIdentifier:
        description: "Please select the environment for deployment"
        type: choice
        required: True
        options:
          - "sbx"
          - "dev"
          - "tst"
          - "prd"

      location:
        description: "Please select the Azure region."
        type: choice
        required: True
        options:
          - australiaeast
          - australiasoutheast

      workloadShortName:
        description: "Workload Short Name"
        type: string
        required: True
        default: ""

      gitHubRepoName:
        description: "GitHub Repository Name"
        type: string
        required: True
        default: ""

env:
  deploymentJobId: "deploy-rg-${{ github.run_id }}"
  gitHubOrganisation: "tulpy"
  oidcAppRegClientId: "a7164fc2-e53c-48a0-8ef8-13c558a9ea95"
  tenantId: "a2ebc691-c318-4ec2-998a-a87c528378e0"
  sbxSubscriptionId: "0b5d0018-2879-4810-b8d7-4f8dda5ce0b9"
  devSubscriptionId: "0b5d0018-2879-4810-b8d7-4f8dda5ce0b9"
  tstSubscriptionId: "0b5d0018-2879-4810-b8d7-4f8dda5ce0b9"
  prdSubscriptionId: "0b5d0018-2879-4810-b8d7-4f8dda5ce0b9"
  spnSbxName: "app-reg-github-${{ inputs.workloadShortName }}-sbx"
  spnDevName: "app-reg-github-${{ inputs.workloadShortName }}-dev"
  spnTstName: "app-reg-github-${{ inputs.workloadShortName }}-tst"
  spnPrdName: "app-reg-github-${{ inputs.workloadShortName }}-prd"

jobs:
  initialise_vars:
    name: Initialise Variables
    runs-on: windows-latest
    outputs:
      sbxSubscriptionId: ${{ env.sbxSubscriptionId }}
      devSubscriptionId: ${{ env.devSubscriptionId }}
      tstSubscriptionId: ${{ env.tstSubscriptionId }}
      prdSubscriptionId: ${{ env.prdSubscriptionId }}
      location: ${{ inputs.location }}
      oidcAppRegClientId: ${{ env.oidcAppRegClientId }}
      tenantId: ${{ env.tenantId }}
      environmentIdentifier: ${{ inputs.environmentIdentifier }}
      solutionShortName: ${{ inputs.workloadShortName }}
      spnSbxName: ${{ env.spnSbxName }}
      spnDevName: ${{ env.spnDevName }}
      spnTstName: ${{ env.spnTstName }}
      spnPrdName: ${{ env.spnPrdName }}
      gitHubRepoName: ${{ inputs.gitHubRepoName }}
      gitHubOrganisation: ${{ env.gitHubOrganisation }}

    steps:
      - name: Initialise Variables
        run: echo "Initialising environment variables"

  deploy_Sbx:
    name: Sandbox
    needs: [initialise_vars]
    if: inputs.environmentIdentifier == 'sbx'
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/deploy-sub.yml
    with:
      gitHubRepoName: ${{ needs.initialise_vars.outputs.gitHubRepoName }}
      gitHubOrganisation: ${{ needs.initialise_vars.outputs.gitHubOrganisation }}
      applicationRegistration: ${{ needs.initialise_vars.outputs.spnSbxName }}
      subscriptionId: ${{ needs.initialise_vars.outputs.sbxSubscriptionId }}
      environmentIdentifier: ${{ needs.initialise_vars.outputs.environmentIdentifier }}
      location: ${{ needs.initialise_vars.outputs.location }}
    secrets: inherit

  deploy_Dev:
    name: Development
    needs: [initialise_vars]
    if: inputs.environmentIdentifier == 'dev'
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/deploy-sub.yml
    with:
      gitHubRepoName: ${{ needs.initialise_vars.outputs.gitHubRepoName }}
      gitHubOrganisation: ${{ needs.initialise_vars.outputs.gitHubOrganisation }}
      applicationRegistration: ${{ needs.initialise_vars.outputs.spnDevName }}
      subscriptionId: ${{ needs.initialise_vars.outputs.devSubscriptionId }}
      environmentIdentifier: ${{ needs.initialise_vars.outputs.environmentIdentifier }}
      location: ${{ needs.initialise_vars.outputs.location }}
    secrets: inherit

  deploy_Tst:
      name: Test
      needs: [initialise_vars]
      if: inputs.environmentIdentifier == 'tst'
      permissions:
        id-token: write
        contents: read
      uses: ./.github/workflows/deploy-sub.yml
      with:
        gitHubRepoName: ${{ needs.initialise_vars.outputs.gitHubRepoName }}
        gitHubOrganisation: ${{ needs.initialise_vars.outputs.gitHubOrganisation }}
        applicationRegistration: ${{ needs.initialise_vars.outputs.spnTstName }}
        subscriptionId: ${{ needs.initialise_vars.outputs.tstSubscriptionId }}
        environmentIdentifier: ${{ needs.initialise_vars.outputs.environmentIdentifier }}
        location: ${{ needs.initialise_vars.outputs.location }}
      secrets: inherit

  deploy_Prd:
        name: Production
        needs: [initialise_vars]
        if: inputs.environmentIdentifier == 'prd'
        permissions:
          id-token: write
          contents: read
        uses: ./.github/workflows/deploy-sub.yml
        with:
          gitHubRepoName: ${{ needs.initialise_vars.outputs.gitHubRepoName }}
          gitHubOrganisation: ${{ needs.initialise_vars.outputs.gitHubOrganisation }}
          applicationRegistration: ${{ needs.initialise_vars.outputs.spnPrdName }}
          subscriptionId: ${{ needs.initialise_vars.outputs.prdSubscriptionId }}
          environmentIdentifier: ${{ needs.initialise_vars.outputs.environmentIdentifier }}
          location: ${{ needs.initialise_vars.outputs.location }}
        secrets: inherit